package com.booyahx.Host;

import android.content.Context;
import android.os.Environment;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;

public class PdfResultGenerator {

    private Context context;

    public PdfResultGenerator(Context context) {
        this.context = context;
    }

    public File generatePdfResult(List<FinalRow> results, String tournamentId) {
        try {
            String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US)
                    .format(System.currentTimeMillis());
            String fileName = "BooyahX_" + tournamentId + "_" + timeStamp + ".pdf";

            File directory = new File(
                    Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES),
                    "BooyahX"
            );

            if (!directory.exists()) {
                directory.mkdirs();
            }

            File pdfFile = new File(directory, fileName);

            PdfWriter writer = new PdfWriter(pdfFile);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);

            // Header
            Paragraph header = new Paragraph("BOOYAH X - FINAL RESULTS")
                    .setFontSize(24)
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontColor(new DeviceRgb(0, 255, 255));
            document.add(header);

            // Theme
            Paragraph theme = new Paragraph("Theme: " + getCurrentTheme())
                    .setFontSize(12)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20);
            document.add(theme);

            // Table
            float[] columnWidths = {50f, 200f, 80f, 80f, 80f, 100f};
            Table table = new Table(UnitValue.createPointArray(columnWidths));
            table.setWidth(UnitValue.createPercentValue(100));

            // Headers
            addHeaderCell(table, "Rank");
            addHeaderCell(table, "Team Name");
            addHeaderCell(table, "Booyah");
            addHeaderCell(table, "Kill Points");
            addHeaderCell(table, "Position Points");
            addHeaderCell(table, "Total Points");

            // Data rows
            for (int i = 0; i < results.size(); i++) {
                FinalRow row = results.get(i);
                boolean isTopThree = i < 3;

                addDataCell(table, String.valueOf(i + 1), isTopThree);
                addDataCell(table, row.teamName, isTopThree);
                addDataCell(table, String.valueOf(row.booyah), isTopThree);
                addDataCell(table, String.valueOf(row.kp), isTopThree);
                addDataCell(table, String.valueOf(row.pp), isTopThree);
                addDataCell(table, String.valueOf(row.total), isTopThree);
            }

            document.add(table);

            // Footer
            Paragraph footer = new Paragraph("\nGenerated by BooyahX Tournament System")
                    .setFontSize(10)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(20);
            document.add(footer);

            document.close();
            return pdfFile;

        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    private void addHeaderCell(Table table, String text) {
        Cell cell = new Cell()
                .add(new Paragraph(text).setBold().setFontSize(12))
                .setBackgroundColor(new DeviceRgb(10, 10, 30))
                .setFontColor(new DeviceRgb(255, 215, 0))
                .setTextAlignment(TextAlignment.CENTER)
                .setPadding(10);
        table.addHeaderCell(cell);
    }

    private void addDataCell(Table table, String text, boolean isTopThree) {
        Paragraph para = new Paragraph(text).setFontSize(11);
        Cell cell = new Cell()
                .add(para)
                .setTextAlignment(TextAlignment.CENTER)
                .setPadding(8);

        if (isTopThree) {
            cell.setBackgroundColor(new DeviceRgb(26, 255, 26))
                    .setFontColor(ColorConstants.BLACK);
        } else {
            cell.setFontColor(ColorConstants.WHITE);
        }

        table.addCell(cell);
    }

    public String getCurrentTheme() {
        Calendar calendar = Calendar.getInstance();
        int hour = calendar.get(Calendar.HOUR_OF_DAY);

        if (hour >= 0 && hour < 6) return "Forest Night";
        else if (hour >= 6 && hour < 12) return "Mystic Blue";
        else if (hour >= 12 && hour < 18) return "Fire Storm";
        else return "Cyber Tech";
    }
}